{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "activepieces.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "activepieces.labels" . | nindent 4 }}
    app.kubernetes.io/component: activepieces
rules:
  {{- if .Values.rbac.rules }}
  {{ toYaml .Values.rbac.rules | nindent 2 }}
  {{- end }}
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "activepieces.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "activepieces.labels" . | nindent 4 }}
    app.kubernetes.io/component: activepieces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "activepieces.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "activepieces.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
