{{- if eq .Values.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "activepieces.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "activepieces.labels" . | nindent 4 }}
spec:
  {{- include "activepieces.podSpec" . | nindent 2 }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.activepieces.data.pvc.reclaimPolicy }}
    whenScaled: {{ .Values.activepieces.data.pvc.reclaimPolicy }}
{{- end }}
