apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gobackup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: gobackup
    {{- include "gobackup.labels" . | nindent 4 }}
    {{- if .Values.configMap.labels }}
    {{- toYaml .Values.configMap.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.configMap.annotations }}
  annotations:
  {{- toYaml .Values.configMap.annotations | nindent 4 }}
  {{- end }}
data:
  gobackup.yml: |
    web:
      port: {{ .Values.gobackup.web.port }}
      {{- if .Values.gobackup.web.host }}
      host: {{ .Values.gobackup.web.host }}
      {{- end }}
      {{- if or .Values.gobackup.web.username .Values.gobackup.web.existingSecret }}
      username: ${WEB_AUTH_USERNAME}
      password: ${WEB_AUTH_PASSWORD}
      {{- end }}
    models:
    {{- /* @formatter:off */ -}}
      {{- range $_, $model := .Values.gobackup.models }}
      {{ $model.name }}:
        {{- include "gobackup.config.templates.base" $model | nindent 8 }}
        {{- if $model.storages }}
        {{- range $_, $storages := $model.storages }}
        {{- /* These templates can't use .name since we're looping through sub-key */ -}}
        {{- $storageParams := set $storages "model" $model.name }}
        storages:
          {{- include "gobackup.config.templates.storage" $storageParams | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if $model.databases }}
        {{- range $_, $databases := $model.databases }}
        {{- $databaseParams := set $databases "model" $model.name }}
        databases:
          {{- include "gobackup.config.templates.database" $databaseParams | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if $model.notifiers }}
        {{- range $_, $notifiers := $model.notifiers }}
        {{- $notifierParams := set $notifiers "model" $model.name }}
        notifiers:
          {{- include "gobackup.config.templates.notifiers" $notifierParams | nindent 10 }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- /* @formatter:on */ -}}
