{{- if and (has "s3" .Values.popeye.scans.destinations) (not .Values.popeye.scans.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "popeye.secret.scans" (dict "type" "s3") }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: popeye
    {{- include "popeye.labels" $ | nindent 4 }}
    {{- if $.Values.secret.labels }}
    {{- toYaml $.Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if $.Values.secret.annotations }}
  annotations:
    {{- toYaml $.Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  accessKey: {{ .Values.popeye.scans.s3.accessKey | b64enc | quote }}
  secretKey: {{ .Values.popeye.scans.s3.secretKey | b64enc | quote }}
{{- end }}
