gobackup:
  workdir: /tmp
  web:
    host: 0.0.0.0
    port: 2703
    username: admin
    password: password

  ## Models configuration
  ## ref: https://gobackup.github.io/configuration
  ##
  models:
    - name: default
      description: Default model
      default: local_default
      schedule:
        cron: "*/5 * * * *"
      scripts:
        before: |
          echo "Running GoBackup model default"
        after: |
          echo "Ran GoBackup model default"

      databases:
        - name: postgresql_default
          type: postgresql
          config:
            host: activepieces-postgresql.default.svc.cluster.local
            port: 5432
            database: activepieces
            username: activepieces
            password: activepieces
          existingSecret: ""

      storages:
        - name: local_default
          type: local
          config:
            path: /tmp/backups
          existingSecret: ""

      notifiers: []
      compression: tgz
      encryption: {}
      archive: {}
      splitter: {}

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: development-issuer
  tls:
    - secretName: gobackup-ingress-tls
      hosts:
        - gobackup.helm.private
  hosts:
    - host: gobackup.helm.private
      paths:
        - path: /
          pathType: ImplementationSpecific
