# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 8.7.0
kubeVersion: ">=1.26.0-0"
name: gotenberg
version: 0.2.2
description: Gotenberg is a Docker-powered stateless API for PDF files.
home: https://gotenberg.dev/
icon: https://user-images.githubusercontent.com/8983173/130322857-185831e2-f041-46eb-a17f-0a69d066c4e5.png
keywords:
  - documents
  - conversion
  - pdf
  - office
  - html
  - markdown
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: fmjstudios
    email: info@fmj.studio
  - name: FMJdev
    email: info@fmj.dev
annotations:
  artifacthub.io/category: streaming-messaging
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: gotenberg
      image: docker.io/gotenberg/gotenberg:8.7.0
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Support
      url: https://github.com/fmjstudios/helm/issues
    - name: Gotenberg Homepage
      url: https://gotenberg.dev/
    - name: Gotenberg Documentation
      url: https://gotenberg.dev/docs/getting-started/introduction
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
  # ref: https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/changes: |
    - kind: fixed
      description: add missing namespace references
    - kind: added
      description: volumes and volumeMounts configuration within values.yaml
    - kind: changed
      description: updated values.schema.json
