# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 1.23.13
kubeVersion: ">=1.26.0-0"
name: uptime-kuma
version: 0.2.2
description: Uptime-Kuma is an open-source, self-hosted fancy uptime monitoring tool
home: https://uptime.kuma.pet/
icon: https://raw.githubusercontent.com/louislam/uptime-kuma/953058c6a5047c82a58606e442c6e572e215e3ff/public/icon-512x512.png
keywords:
  - uptime
  - monitoring
  - website
  - database
  - tls
  - uptime-robot
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: fmjstudios
    email: info@fmj.studio
  - name: FMJdev
    email: info@fmj.dev
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: uptime-kuma
      image: docker.io/louislam/uptime-kuma:1.23.13
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Support
      url: https://github.com/fmjstudios/helm/issues
    - name: Uptime-Kuma Homepage
      url: https://uptime.kuma.pet/
    - name: Uptime-Kuma Documentation
      url: https://github.com/louislam/uptime-kuma/wiki
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
  # ref: https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/changes: |
    - kind: fixed
      description: add missing namespace references
    - kind: added
      description: volumes and volumeMounts configuration within values.yaml
    - kind: changed
      description: updated values.schema.json
