vaultwarden:
  domain: "vaultwarden.helm.private"
  adminToken:
    value: "PretendThisIsAnAdminToken"

    smtp:
      host: ""
      from: ""
      fromName: "Vaultwarden"
      security: "starttls"
      port: 587
      username: ""
      password: ""
      auth: "Plain"
      helloName: "vaultwarden.helm.private"
      acceptInvalidHostnames: true
      acceptInvalidCertificates: true

  database:
    type: "sqlite"
    enableWAL: true

  signup:
    allowed: true
    verify: false
    domainWhitelist: "fmj.studio,helm.private"

  logs:
    level: debug
    extended: true

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: development-issuer
  tls:
    - secretName: vaultwarden-ingress-tls
      hosts:
        - "vaultwarden.helm.private"

rbac:
  create: true

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true
