apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gotenberg.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gotenberg.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "gotenberg.selectorLabels" . | nindent 6 }}
  {{- if .Values.strategy -}}
  strategy:
  {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "gotenberg.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels -}}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gotenberg.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - gotenberg
          {{- /*
            API settings
          */}}
            - --api-port={{ .Values.gotenberg.api.port }}
          {{- if ne .Values.gotenberg.api.startTimeout "30s" }}
            - --api-start-timeout={{ .Values.gotenberg.api.startTimeout }}
          {{- end }}
          {{- if ne .Values.gotenberg.api.timeout "30s" }}
            - --api-timeout={{ .Values.gotenberg.api.timeout }}
          {{- end }}
          {{- if ne .Values.gotenberg.api.rootPath "/" }}
            - --api-root-path={{ .Values.gotenberg.api.rootPath }}
          {{- end }}
          {{- if .Values.gotenberg.api.traceHeader }}
            - --api-trace-header={{ .Values.gotenberg.api.traceHeader }}
          {{- end }}
          {{- if .Values.gotenberg.api.disableHealthCheckLogging }}
            - --api-disable-health-check-logging={{ .Values.gotenberg.api.disableHealthCheckLogging }}
          {{- end }}
          {{- /*
            HTTP BasicAuth settings
          */}}
          {{- if .Values.gotenberg.basicAuth.enabled }}
            - --api-enable-basic-auth={{ .Values.gotenberg.basicAuth.enabled }}
          {{- end }}
          {{- /*
            Chromium settings
          */}}
          {{- if ne (.Values.gotenberg.chromium.restartAfter | toString) "0" }}
            - --chromium-restart-after={{ .Values.gotenberg.chromium.restartAfter }}
          {{- end }}
          {{- if ne (.Values.gotenberg.chromium.maxQueueSize | toString) "0" }}
            - --chromium-max-queue-size={{ .Values.gotenberg.chromium.maxQueueSize }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.autoStart }}
            - --chromium-auto-start={{ .Values.gotenberg.chromium.autoStart }}
          {{- end }}
          {{- if ne .Values.gotenberg.chromium.startTimeout "20s" }}
            - --chromium-start-timeout={{ .Values.gotenberg.chromium.startTimeout }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.allowFileAccessFromFiles }}
            - --chromium-allow-file-access-from-files={{ .Values.gotenberg.chromium.allowFileAccessFromFiles }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.allowInsecureLocalhost }}
            - --chromium-allow-insecure-localhost={{ .Values.gotenberg.chromium.allowInsecureLocalhost }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.allowList }}
            - --chromium-allow-list={{ .Values.gotenberg.chromium.allowList }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.denyList }}
            - --chromium-deny-list={{ .Values.gotenberg.chromium.denyList }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.ignoreCertificateErrors }}
            - --chromium-ignore-certificate-errors={{ .Values.gotenberg.chromium.ignoreCertificateErrors }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.disableWebSecurity }}
            - --chromium-disable-web-security={{ .Values.gotenberg.chromium.disableWebSecurity }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.incognito }}
            - --chromium-incognito={{ .Values.gotenberg.chromium.incognito }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.hostResolverRules }}
            - --chromium-host-resolver-rules={{ .Values.gotenberg.chromium.hostResolverRules }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.proxyServer }}
            - --chromium-proxy-server={{ .Values.gotenberg.chromium.proxyServer }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.clearCache }}
            - --chromium-clear-cache={{ .Values.gotenberg.chromium.clearCache }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.clearCookies }}
            - --chromium-clear-cookies={{ .Values.gotenberg.chromium.clearCookies }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.disableJavaScript }}
            - --chromium-disable-javascript={{ .Values.gotenberg.chromium.disableJavaScript }}
          {{- end }}
          {{- if .Values.gotenberg.chromium.disableRoutes }}
            - --chromium-disable-routes={{ .Values.gotenberg.chromium.disableRoutes }}
          {{- end }}
          {{- /*
            LibreOffice settings
          */}}
          {{- if ne (.Values.gotenberg.libreOffice.restartAfter | toString) "10" }}
            - --libreoffice-restart-after={{ .Values.gotenberg.libreOffice.restartAfter }}
          {{- end }}
          {{- if ne (.Values.gotenberg.libreOffice.maxQueueSize | toString) "0" }}
            - --libreoffice-max-queue-size={{ .Values.gotenberg.libreOffice.maxQueueSize }}
          {{- end }}
          {{- if .Values.gotenberg.libreOffice.autoStart }}
            - --libreoffice-auto-start={{ .Values.gotenberg.libreOffice.autoStart }}
          {{- end }}
          {{- if ne .Values.gotenberg.libreOffice.startTimeout "20s" }}
            - --libreoffice-start-timeout={{ .Values.gotenberg.libreOffice.startTimeout }}
          {{- end }}
          {{- if .Values.gotenberg.libreOffice.disableRoutes }}
            - --libreoffice-disable-routes={{ .Values.gotenberg.libreOffice.disableRoutes }}
          {{- end }}
          {{- /*
            PDF settings
          */}}
          {{- if .Values.gotenberg.pdf.engines }}
            - --pdfengines-engines={{ .Values.gotenberg.pdf.engines }}
          {{- end }}
          {{- if .Values.gotenberg.pdf.disableRoutes }}
            - --pdfengines-disable-routes={{ .Values.gotenberg.pdf.disableRoutes }}
          {{- end }}
          {{- /*
            Webhook settings
          */}}
          {{- if .Values.gotenberg.webhook.allowList }}
            - --webhook-allow-list={{ .Values.gotenberg.webhook.allowList }}
          {{- end }}
          {{- if .Values.gotenberg.webhook.denyList }}
            - --webhook-deny-list={{ .Values.gotenberg.webhook.denyList }}
          {{- end }}
          {{- if .Values.gotenberg.webhook.errorAllowList }}
            - --webhook-error-allow-list={{ .Values.gotenberg.webhook.errorAllowList }}
          {{- end }}
          {{- if .Values.gotenberg.webhook.errorDenyList }}
            - --webhook-error-deny-list={{ .Values.gotenberg.webhook.errorDenyList }}
          {{- end }}
          {{- if ne (.Values.gotenberg.webhook.maxRetry | toString) "4" }}
            - --webhook-max-retry={{ .Values.gotenberg.webhook.maxRetry }}
          {{- end }}
          {{- if ne .Values.gotenberg.webhook.retryMinWait "1s" }}
            - --webhook-retry-min-wait={{ .Values.gotenberg.webhook.retryMinWait }}
          {{- end }}
          {{- if ne .Values.gotenberg.webhook.retryMaxWait "30s" }}
            - --webhook-retry-max-wait={{ .Values.gotenberg.webhook.retryMaxWait }}
          {{- end }}
          {{- if ne .Values.gotenberg.webhook.clientTimeout "30s" }}
            - --webhook-client-timeout={{ .Values.gotenberg.webhook.clientTimeout }}
          {{- end }}
          {{- if .Values.gotenberg.webhook.disable }}
            - --webhook-disable={{ .Values.gotenberg.webhook.disable }}
          {{- end }}
          {{- /*
            Prometheus settings
          */}}
          {{- if .Values.gotenberg.prometheus.collectInterval }}
            - --prometheus-collect-interval={{ .Values.gotenberg.prometheus.collectInterval }}
          {{- end }}
          {{- if .Values.gotenberg.prometheus.namespace }}
            - --prometheus-namespace={{ .Values.gotenberg.prometheus.namespace }}
          {{- end }}
          {{- if .Values.gotenberg.prometheus.disableCollect }}
            - --prometheus-disable-collect={{ .Values.gotenberg.prometheus.disableCollect }}
          {{- end }}
          {{- if .Values.gotenberg.prometheus.disableRouteLogging }}
            - --prometheus-disable-route-logging={{ .Values.gotenberg.prometheus.disableRouteLogging }}
          {{- end }}
          {{- /*
            Logging settings
          */}}
          {{- if .Values.gotenberg.logging.format }}
            - --log-format={{ .Values.gotenberg.logging.format }}
          {{- end }}
          {{- if .Values.gotenberg.logging.level }}
            - --log-level={{ .Values.gotenberg.logging.level }}
          {{- end }}
          {{- if .Values.gotenberg.logging.fieldsPrefix }}
            - --log-fields-prefix={{ .Values.gotenberg.logging.fieldsPrefix }}
          {{- end }}
          {{- /*
            Shutdown settings
          */}}
          {{- if ne .Values.gotenberg.shutdown.duration "30s" }}
            - --gotenberg-graceful-shutdown-duration={{ .Values.gotenberg.shutdown.duration }}
          {{- end }}
          env:
            {{- if .Values.gotenberg.basicAuth.enabled }}
            - name: GOTENBERG_API_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "gotenberg.secret.auth" .) .Values.gotenberg.basicAuth.existingSecret }}
                  key: username
            - name: GOTENBERG_API_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "gotenberg.secret.auth" .) .Values.gotenberg.basicAuth.existingSecret }}
                  key: password
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.gotenberg.api.port }}
              protocol: TCP
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.volumes}}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
