{{- if (not .Values.gotenberg.basicAuth.existingSecret ) -}}
{{- /*
HTTP Basic Auth secret
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gotenberg.secret.auth" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: gotenberg
    {{ include "gotenberg.labels" $ | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: "kubernetes.io/basic-auth"
data:
  username: {{ .Values.gotenberg.basicAuth.username | b64enc | quote }}
  password: {{ .Values.gotenberg.basicAuth.password | b64enc | quote }}
{{- end }}
