# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 2.3.15
kubeVersion: ">=1.26.0-0"
name: cachet
version: 0.2.2
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    version: ~15.5
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
    version: ~19.5
description: Cachet is an open-source status page system designed to help you keep track of your system status and share it with your user base
home: https://cachethq.io/
icon: https://raw.githubusercontent.com/cachethq/art/1a545d3ae52df6ee4d22677acfcc6ab4a90ef231/logo-mark/cachet-logomark-green.png
keywords:
  - status
  - status-page
  - uptime
  - monitoring
  - uptime-kuma
  - cachet
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: fmjstudios
    email: info@fmj.studio
  - name: FMJdev
    email: info@fmj.dev
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: cachet
      image: docker.io/cachethq/docker:2.3.15
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Support
      url: https://github.com/fmjstudios/helm/issues
    - name: Cachet Homepage
      url: https://cachethq.io/
    - name: Cachet Documentation
      url: https://docs.cachethq.io/introduction.html
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
  # ref: https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/changes: |
    - kind: fixed
      description: add missing namespace references
    - kind: added
      description: volumes and volumeMounts configuration within values.yaml
    - kind: changed
      description: updated values.schema.json
